<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="database" Id="{143714b2-f4fe-44a5-9694-f19cd8ef93e2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM database
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="database">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>